# Generated by Django 5.1.4 on 2025-02-20 00:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suplier_name', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='products', verbose_name='Imagem Do Produto')),
                ('product_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome')),
                ('product_code', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Codigo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preco')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='data de criacao')),
                ('categories', models.ManyToManyField(related_name='questions', to='app_models_test.category')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_models_test.suplier')),
            ],
        ),
    ]
