# Generated by Django 5.1.4 on 2024-12-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome')),
                ('product_code', models.CharField(max_length=200, unique=True, verbose_name='Codigo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='data de criacao')),
            ],
        ),
    ]
