# Generated by Django 5.1.4 on 2024-12-12 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suplier_name', models.CharField(blank=True, max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=14, verbose_name='Nome')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='questions', to='app_models_test.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='suplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_models_test.suplier'),
            preserve_default=False,
        ),
    ]
